-- 1. Create Ledgers table
CREATE TABLE ledgers (
    ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add ledger_id to transactions
ALTER TABLE transactions 
ADD COLUMN ledger_id BIGINT REFERENCES ledgers(ledger_id) ON DELETE CASCADE;

-- 3. Add ledger_id to amount_limit
ALTER TABLE amount_limit 
ADD COLUMN ledger_id BIGINT REFERENCES ledgers(ledger_id) ON DELETE CASCADE;

-- 4. Add ledger_id to expense_type
ALTER TABLE expense_type 
ADD COLUMN ledger_id BIGINT REFERENCES ledgers(ledger_id) ON DELETE CASCADE;

-- 5. Data Migration: Create a default ledger for existing users
INSERT INTO ledgers (user_id, name, is_default)
SELECT id, 'Personal', TRUE FROM auth.users;

-- 6. Assign existing data to the new default ledger
UPDATE transactions t 
SET ledger_id = l.ledger_id 
FROM ledgers l 
WHERE t.user_id = l.user_id AND l.is_default = TRUE;

UPDATE amount_limit al 
SET ledger_id = l.ledger_id 
FROM ledgers l 
WHERE al.user_id = l.user_id AND l.is_default = TRUE;

UPDATE expense_type et 
SET ledger_id = l.ledger_id 
FROM ledgers l 
WHERE et.user_id = l.user_id AND l.is_default = TRUE;
