-- 1. Create Ledgers table
CREATE TABLE ledgers (
    ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add ledger_id to transactions
ALTER TABLE transactions 
ADD COLUMN ledger_id BIGINT REFERENCES ledgers(ledger_id) ON DELETE CASCADE;

-- 3. Add ledger_id to amount_limit
ALTER TABLE amount_limit 
ADD COLUMN ledger_id BIGINT REFERENCES ledgers(ledger_id) ON DELETE CASCADE;

-- 4. Add ledger_id to expense_type
ALTER TABLE expense_type 
ADD COLUMN ledger_id BIGINT REFERENCES ledgers(ledger_id) ON DELETE CASCADE;

-- 5. Data Migration: Create a default ledger for existing users
INSERT INTO ledgers (user_id, name, is_default)
SELECT user_id, 'Personal', TRUE FROM users;

-- 6. Assign existing data to the new default ledger
UPDATE transactions t 
SET ledger_id = l.ledger_id 
FROM ledgers l 
WHERE t.user_id = l.user_id AND l.is_default = TRUE;

UPDATE amount_limit al 
SET ledger_id = l.ledger_id 
FROM ledgers l 
WHERE al.user_id = l.user_id AND l.is_default = TRUE;

UPDATE expense_type et 
SET ledger_id = l.ledger_id 
FROM ledgers l 
WHERE et.user_id = l.user_id AND l.is_default = TRUE;

-- 7. Update get_daily_totals function to accept p_ledger_id
OR REPLACE FUNCTION get_daily_totals(
    p_user_id UUID,
    p_ledger_id BIGINT,
    p_from_date DATE,
    p_to_date DATE
)
RETURNS TABLE (
    transaction_date DATE,
    total_amount NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        date::DATE as transaction_date,
        COALESCE(SUM(amount), 0) as total_amount
    FROM transactions
    WHERE user_id = p_user_id
      AND ledger_id = p_ledger_id
      AND date::DATE BETWEEN p_from_date AND p_to_date
    GROUP BY date::DATE
    ORDER BY transaction_date;
END;
$$ LANGUAGE plpgsql;
